### ISSUE TITLE
Could not find service `main-router`, available services: `main-router`

### ISSUE THREAD

**Issue by henres** [samber/do#10]
Hello, thanks for your great works.

here the specs :
```
github.com/samber/do v1.2.0 
go 1.18
```
Maybe I don't understand something ?
I tried to generate gin router and retrieved it to run the server.
But it doesn't work :'(

Here what I tried :

```golang
package main

import (
	"github.com/gin-gonic/gin"
	glog "github.com/magicsong/color-glog"
	"github.com/samber/do"
)

func generateContainer() *do.Injector {
	injector := do.New()

	do.ProvideNamedValue(injector, "main-router", gin.Default())
	
	return injector
}

func main() {
	container := generateContainer()

	router := do.MustInvokeNamed[gin.Engine](container, "main-router")
	if err := router.Run(); err != nil {
		glog.Fatal(err)
	}
}
```

And the error :

```
panic: DI: could not find service `main-router`, available services: `main-router`
```

Is it possible to have some help.

**Comment by henres** [comment]
I think, the problem come from the type of value is not corresponding to gin.Engine.

**Comment by samber** [comment]
Named services should be used only when you have no other choice, or when you boot multiple times a single service.

In other cases, you should use `ProvideValue[gin.Engine]` + `MustInvoke[gin.Engine]`
