### ISSUE TITLE
[Feature Request] Method aliases skipping "injector" argument (default injector)

### ISSUE THREAD

**Issue by kcmvp** [samber/do#17]
- Service register
`func ProvideNamedValue[T any](i *Injector, name string, value T) {`
`func Provide[T any](i *Injector, provider Provider[T]) {`

- Service lookup
`func InvokeNamed[T any](i *Injector, name string) (T, error) {`

for these two group method, it can accept a **nil** Injector, in this case then it will use system default Injector.

can we supply another group of API without the ** *Injector** parameter to make a simpler API?

**Comment by kcmvp** [comment]
If it supports this set of API then
`	do.Provide(nil, config)
	do.Provide(nil, datasource)
	do.Provide(nil, db)`

can be writtern as 

`	do.Provide(config)
	do.Provide(datasource)
	do.Provide(db)`

it's much more clean

**Comment by samber** [comment]
Thanks for your suggestion, but I'm not sure we will add these shortcuts to the repository.

Using default injectors is basically a bad idea since it makes your code very hard to test. Adding 18 more helpers without the `i *do.Injector` argument seems excessive to me.

Anyway, you can use a simple alias in your projects:

```go
// utils/do.go
func Provide(provider do.Provider[T]) {
    return do.Provide(nil, provider)
}
```

I keep this issue open for further discussion. If anybody wants to expose a PoV, please answer this issue!

**Comment by kcmvp** [comment]
> Thanks for your suggestion, but I'm not sure we will add these shortcuts to the repository.
> 
> Using default injectors is basically a bad idea since it makes your code very hard to test. Adding 18 more helpers without the `i *do.Injector` argument seems excessive to me.
> 
> Anyway, you can use a simple alias in your projects:
> 
> ```go
> // utils/do.go
> func Provide(provider do.Provider[T]) {
>     return do.Provide(nil, provider)
> }
> ```
> 
> I keep this issue open for further discussion. If anybody wants to expose a PoV, please answer this issue!

> Using default injectors is basically a bad idea since it makes your code very hard to test

Agree with you about this point. in fact I think about this issue.  right now for me I just use the **DefaultInjector** directly for unit test. from the respect of API user he need to know the detail design of the library.

another benefit of **Method aliases** is that we dont need  to pass around the **variable** around. I can get it just when I want. 

might be **a global function is better than a global variable**.

change 
`var DefaultInjector = New()`
to

`
func DefaultInjector() *Injector {}
`

**Comment by samber** [comment]
Closing, since it has been added to the project under `do.DefaultInjector`
