### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by mtiller** [samber/do#21]
Would you be interested in a PR that adds standard `http` based middleware?  The ideal is that it provides middleware that adds the `injector` to the request context and then, in each request, you can quickly fetch not just the `injector` instance itself but also request specific services out of the injector while handling requests.  Seems like it would be generally useful for anybody doing web development using `do` and it doesn't add any dependencies since it is based on the standard library.

I've written such a thing and it would be useful to include here since otherwise I'd have to make a tiny package and publish it just to reuse it across projects.

**Comment by samber** [comment]
Hi @mtiller and thanks for the proposal.

Could you please provide a quick demo of the API you imagined?

I don't think it's the right place for such a feature, since `do` is intended to be a low-level DI library. However, a sub-package or `do-contrib` library could be a nice option.
