### ISSUE TITLE
ServiceLazy shutdowm method

### ISSUE THREAD

**Issue by hesining** [samber/do#23]
``` go
func (s *ServiceLazy[T]) shutdown() error {
	instance, ok := any(s.instance).(Shutdownable)
	if ok {
		return instance.Shutdown()
	}

	s.built = false
	s.instance = empty[T]()
	return nil

}
```

Is it necessary for ‘shutdown’  not return, continue to set the 'build' and 'instance'  field?

**Comment by hesining** [comment]
> I agree. Would you like to make a fix+tests?

OK,I'll try.

**Comment by hesining** [comment]
> I agree. Would you like to make a fix+tests?

I fixed it, please check.
https://github.com/samber/do/pull/24

**Comment by samber** [comment]
Thanks for your help ;)

Please upgrade to v1.5.1
