### ISSUE TITLE
Possible use of closed services in main() on shutdown

### ISSUE THREAD

**Issue by pavelpatrin** [samber/do#26]
Hi. Your example code shows us, that it is OK to define services by specifying factories and next get it from the container with the function `do.MustInvoke[...](x)`.

Lets imagine we have following code (based on readme example)

```go
func main() {
    injector := do.New()

    // provides CarService
    do.Provide(injector, NewCarService)

    // provides EngineService
    do.Provide(injector, NewEngineService)

    car := do.MustInvoke[*CarService](injector)
    ch := make(chan struct{})
 
    // run background goroutine with stop chan
    go (func(){
        for {
        select {
        case <-ch:
            return
        default:
            car.Beep()  // service may be already closed
            time.Sleep(1s)
        }
        }
    })()

    injector.ShutdownOnSIGTERM()    // will block until receiving sigterm signal
    close(ch)  // stop the goroutine, but only after container shutdown
}
```

Here we have no API to let the `main()` code know that container is wanting to shutdown and await the reaction from `main()` for this event BEFORE starting the shutdown. This may trigger misuse of the container by users.

Solutions.

* Force users to don't start background goroutines from `main()` code which uses services spawned by the container. Instead, users should implement services with right `Shutdown()` implementation to allow the container manage services life times. I.e. users should implement `glue code services`.
* Implement API that allows to define `Shutdown` function for the `main()` code, to allow the `main()` stop working with the services **before** they starts shutdown.

**Comment by pavelpatrin** [comment]
In my own Service Container implementation (written for my company, not public) I had chose first case.

**Comment by samber** [comment]
In this case, I would suggest moving the event loop into a dedicated service that depends on `Car` and implementing `Shutdownable` interface.

On SIGTERM signal, the `Shutdown()` handler of the new service will be called first. Calling `close(ch)` will stop the event loop. Then the `Car` service will be shutdown, then `EngineService`, then...
